services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  flask:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql